/*
  File autogenerated by gengetopt version 2.23
  generated with the following command:
  /usr/bin/gengetopt -S --set-package=lwfs-tests --set-version=0.1 --file-name=lwfs-opts 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef FIX_UNUSED
#define FIX_UNUSED(X) (void) (X) /* avoid warnings for unused params */
#endif

#include <getopt.h>

#include "lwfs-opts.h"

const char *gengetopt_args_info_purpose = "";

const char *gengetopt_args_info_usage = "Usage: lwfs-tests [OPTION]...";

const char *gengetopt_args_info_versiontext = "";

const char *gengetopt_args_info_description = "";

const char *gengetopt_args_info_help[] = {
  "  -h, --help                    Print help and exit",
  "  -V, --version                 Print version and exit",
  "      --num-trials=INT          The number of trials per experiment\n                                  (default=`1')",
  "      --ops-per-trial=INT       The number of operations in a trial\n                                  (blocksize=ops_per_trial*bytes_per_op)\n                                  (default=`1')",
  "      --bytes-per-op=INT        The number of bytes/object  (default=`1024')",
  "      --num-ost=INT             The number of object storage targets\n                                  (default=`1')",
  "      --num-stripe=INT          The number of stripes/file  (default=`1')",
  "      --stripe-size=LONG        The size of a stripe  (default=`1')",
  "      --async                   Asynchronous tests  (default=off)",
  "      --in-transit=INT          Number of requests in transit  (default=`10')",
  "      --result-file=STRING      Where to store results",
  "      --result-file-mode=STRING Write mode for the result  (possible\n                                  values=\"write\", \"append\" default=`write')",
  "      --scratch-file=STRING     Where to write scratch data\n                                  (default=`/usr/tmp/scratch')",
  "      --remove-file             Remove the file when finished  (default=off)",
  "      --lwfs-config-file=STRING Configuration file for LWFS services",
    0
};

typedef enum {ARG_NO
  , ARG_FLAG
  , ARG_STRING
  , ARG_INT
  , ARG_LONG
} cmdline_parser_arg_type;

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error);

static int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error);
struct line_list
{
  char * string_arg;
  struct line_list * next;
};

static struct line_list *cmd_line_list = 0;
static struct line_list *cmd_line_list_tmp = 0;

static void
free_cmd_list(void)
{
  /* free the list of a previous call */
  if (cmd_line_list)
    {
      while (cmd_line_list) {
        cmd_line_list_tmp = cmd_line_list;
        cmd_line_list = cmd_line_list->next;
        free (cmd_line_list_tmp->string_arg);
        free (cmd_line_list_tmp);
      }
    }
}


const char *cmdline_parser_result_file_mode_values[] = {"write", "append", 0}; /*< Possible values for result-file-mode. */

static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->num_trials_given = 0 ;
  args_info->ops_per_trial_given = 0 ;
  args_info->bytes_per_op_given = 0 ;
  args_info->num_ost_given = 0 ;
  args_info->num_stripe_given = 0 ;
  args_info->stripe_size_given = 0 ;
  args_info->async_given = 0 ;
  args_info->in_transit_given = 0 ;
  args_info->result_file_given = 0 ;
  args_info->result_file_mode_given = 0 ;
  args_info->scratch_file_given = 0 ;
  args_info->remove_file_given = 0 ;
  args_info->lwfs_config_file_given = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  FIX_UNUSED (args_info);
  args_info->num_trials_arg = 1;
  args_info->num_trials_orig = NULL;
  args_info->ops_per_trial_arg = 1;
  args_info->ops_per_trial_orig = NULL;
  args_info->bytes_per_op_arg = 1024;
  args_info->bytes_per_op_orig = NULL;
  args_info->num_ost_arg = 1;
  args_info->num_ost_orig = NULL;
  args_info->num_stripe_arg = 1;
  args_info->num_stripe_orig = NULL;
  args_info->stripe_size_arg = 1;
  args_info->stripe_size_orig = NULL;
  args_info->async_flag = 0;
  args_info->in_transit_arg = 10;
  args_info->in_transit_orig = NULL;
  args_info->result_file_arg = NULL;
  args_info->result_file_orig = NULL;
  args_info->result_file_mode_arg = gengetopt_strdup ("write");
  args_info->result_file_mode_orig = NULL;
  args_info->scratch_file_arg = gengetopt_strdup ("/usr/tmp/scratch");
  args_info->scratch_file_orig = NULL;
  args_info->remove_file_flag = 0;
  args_info->lwfs_config_file_arg = NULL;
  args_info->lwfs_config_file_orig = NULL;
  
}

static
void init_args_info(struct gengetopt_args_info *args_info)
{


  args_info->help_help = gengetopt_args_info_help[0] ;
  args_info->version_help = gengetopt_args_info_help[1] ;
  args_info->num_trials_help = gengetopt_args_info_help[2] ;
  args_info->ops_per_trial_help = gengetopt_args_info_help[3] ;
  args_info->bytes_per_op_help = gengetopt_args_info_help[4] ;
  args_info->num_ost_help = gengetopt_args_info_help[5] ;
  args_info->num_stripe_help = gengetopt_args_info_help[6] ;
  args_info->stripe_size_help = gengetopt_args_info_help[7] ;
  args_info->async_help = gengetopt_args_info_help[8] ;
  args_info->in_transit_help = gengetopt_args_info_help[9] ;
  args_info->result_file_help = gengetopt_args_info_help[10] ;
  args_info->result_file_mode_help = gengetopt_args_info_help[11] ;
  args_info->scratch_file_help = gengetopt_args_info_help[12] ;
  args_info->remove_file_help = gengetopt_args_info_help[13] ;
  args_info->lwfs_config_file_help = gengetopt_args_info_help[14] ;
  
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n",
     (strlen(CMDLINE_PARSER_PACKAGE_NAME) ? CMDLINE_PARSER_PACKAGE_NAME : CMDLINE_PARSER_PACKAGE),
     CMDLINE_PARSER_VERSION);

  if (strlen(gengetopt_args_info_versiontext) > 0)
    printf("\n%s\n", gengetopt_args_info_versiontext);
}

static void print_help_common(void)
{
	size_t len_purpose = strlen(gengetopt_args_info_purpose);
	size_t len_usage = strlen(gengetopt_args_info_usage);

	if (len_usage > 0) {
		printf("%s\n", gengetopt_args_info_usage);
	}
	if (len_purpose > 0) {
		printf("%s\n", gengetopt_args_info_purpose);
	}

	if (len_usage || len_purpose) {
		printf("\n");
	}

	if (strlen(gengetopt_args_info_description) > 0) {
		printf("%s\n\n", gengetopt_args_info_description);
	}
}

void
cmdline_parser_print_help (void)
{
  int i = 0;
  print_help_common();
  while (gengetopt_args_info_help[i])
    printf("%s\n", gengetopt_args_info_help[i++]);
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);
}

void
cmdline_parser_params_init(struct cmdline_parser_params *params)
{
  if (params)
    { 
      params->override = 0;
      params->initialize = 1;
      params->check_required = 1;
      params->check_ambiguity = 0;
      params->print_errors = 1;
    }
}

struct cmdline_parser_params *
cmdline_parser_params_create(void)
{
  struct cmdline_parser_params *params = 
    (struct cmdline_parser_params *)malloc(sizeof(struct cmdline_parser_params));
  cmdline_parser_params_init(params);  
  return params;
}

static void
free_string_field (char **s)
{
  if (*s)
    {
      free (*s);
      *s = 0;
    }
}


static void
cmdline_parser_release (struct gengetopt_args_info *args_info)
{

  free_string_field (&(args_info->num_trials_orig));
  free_string_field (&(args_info->ops_per_trial_orig));
  free_string_field (&(args_info->bytes_per_op_orig));
  free_string_field (&(args_info->num_ost_orig));
  free_string_field (&(args_info->num_stripe_orig));
  free_string_field (&(args_info->stripe_size_orig));
  free_string_field (&(args_info->in_transit_orig));
  free_string_field (&(args_info->result_file_arg));
  free_string_field (&(args_info->result_file_orig));
  free_string_field (&(args_info->result_file_mode_arg));
  free_string_field (&(args_info->result_file_mode_orig));
  free_string_field (&(args_info->scratch_file_arg));
  free_string_field (&(args_info->scratch_file_orig));
  free_string_field (&(args_info->lwfs_config_file_arg));
  free_string_field (&(args_info->lwfs_config_file_orig));
  
  

  clear_given (args_info);
}

/**
 * @param val the value to check
 * @param values the possible values
 * @return the index of the matched value:
 * -1 if no value matched,
 * -2 if more than one value has matched
 */
static int
check_possible_values(const char *val, const char *values[])
{
  int i, found, last;
  size_t len;

  if (!val)   /* otherwise strlen() crashes below */
    return -1; /* -1 means no argument for the option */

  found = last = 0;

  for (i = 0, len = strlen(val); values[i]; ++i)
    {
      if (strncmp(val, values[i], len) == 0)
        {
          ++found;
          last = i;
          if (strlen(values[i]) == len)
            return i; /* exact macth no need to check more */
        }
    }

  if (found == 1) /* one match: OK */
    return last;

  return (found ? -2 : -1); /* return many values or none matched */
}


static void
write_into_file(FILE *outfile, const char *opt, const char *arg, const char *values[])
{
  int found = -1;
  if (arg) {
    if (values) {
      found = check_possible_values(arg, values);      
    }
    if (found >= 0)
      fprintf(outfile, "%s=\"%s\" # %s\n", opt, arg, values[found]);
    else
      fprintf(outfile, "%s=\"%s\"\n", opt, arg);
  } else {
    fprintf(outfile, "%s\n", opt);
  }
}


int
cmdline_parser_dump(FILE *outfile, struct gengetopt_args_info *args_info)
{
  int i = 0;

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot dump options to stream\n", CMDLINE_PARSER_PACKAGE);
      return EXIT_FAILURE;
    }

  if (args_info->help_given)
    write_into_file(outfile, "help", 0, 0 );
  if (args_info->version_given)
    write_into_file(outfile, "version", 0, 0 );
  if (args_info->num_trials_given)
    write_into_file(outfile, "num-trials", args_info->num_trials_orig, 0);
  if (args_info->ops_per_trial_given)
    write_into_file(outfile, "ops-per-trial", args_info->ops_per_trial_orig, 0);
  if (args_info->bytes_per_op_given)
    write_into_file(outfile, "bytes-per-op", args_info->bytes_per_op_orig, 0);
  if (args_info->num_ost_given)
    write_into_file(outfile, "num-ost", args_info->num_ost_orig, 0);
  if (args_info->num_stripe_given)
    write_into_file(outfile, "num-stripe", args_info->num_stripe_orig, 0);
  if (args_info->stripe_size_given)
    write_into_file(outfile, "stripe-size", args_info->stripe_size_orig, 0);
  if (args_info->async_given)
    write_into_file(outfile, "async", 0, 0 );
  if (args_info->in_transit_given)
    write_into_file(outfile, "in-transit", args_info->in_transit_orig, 0);
  if (args_info->result_file_given)
    write_into_file(outfile, "result-file", args_info->result_file_orig, 0);
  if (args_info->result_file_mode_given)
    write_into_file(outfile, "result-file-mode", args_info->result_file_mode_orig, cmdline_parser_result_file_mode_values);
  if (args_info->scratch_file_given)
    write_into_file(outfile, "scratch-file", args_info->scratch_file_orig, 0);
  if (args_info->remove_file_given)
    write_into_file(outfile, "remove-file", 0, 0 );
  if (args_info->lwfs_config_file_given)
    write_into_file(outfile, "lwfs-config-file", args_info->lwfs_config_file_orig, 0);
  

  i = EXIT_SUCCESS;
  return i;
}

int
cmdline_parser_file_save(const char *filename, struct gengetopt_args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  i = cmdline_parser_dump(outfile, args_info);
  fclose (outfile);

  return i;
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  cmdline_parser_release (args_info);
}

/** @brief replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = 0;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

int
cmdline_parser (int argc, char **argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser_ext (int argc, char **argv, struct gengetopt_args_info *args_info,
                   struct cmdline_parser_params *params)
{
  int result;
  result = cmdline_parser_internal (argc, argv, args_info, params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser2 (int argc, char **argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;
  struct cmdline_parser_params params;
  
  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  result = cmdline_parser_internal (argc, argv, args_info, &params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  int result = EXIT_SUCCESS;

  if (cmdline_parser_required2(args_info, prog_name, 0) > 0)
    result = EXIT_FAILURE;

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error)
{
  int error_occurred = 0;
  FIX_UNUSED (additional_error);

  /* checks for required options */
  
  /* checks for dependences among options */
  if (args_info->in_transit_given && ! args_info->async_given)
    {
      fprintf (stderr, "%s: '--in-transit' option depends on option 'async'%s\n", prog_name, (additional_error ? additional_error : ""));
      error_occurred = 1;
    }

  return error_occurred;
}


static char *package_name = 0;

/**
 * @brief updates an option
 * @param field the generic pointer to the field to update
 * @param orig_field the pointer to the orig field
 * @param field_given the pointer to the number of occurrence of this option
 * @param prev_given the pointer to the number of occurrence already seen
 * @param value the argument for this option (if null no arg was specified)
 * @param possible_values the possible values for this option (if specified)
 * @param default_value the default value (in case the option only accepts fixed values)
 * @param arg_type the type of this option
 * @param check_ambiguity @see cmdline_parser_params.check_ambiguity
 * @param override @see cmdline_parser_params.override
 * @param no_free whether to free a possible previous value
 * @param multiple_option whether this is a multiple option
 * @param long_opt the corresponding long option
 * @param short_opt the corresponding short option (or '-' if none)
 * @param additional_error possible further error specification
 */
static
int update_arg(void *field, char **orig_field,
               unsigned int *field_given, unsigned int *prev_given, 
               char *value, const char *possible_values[],
               const char *default_value,
               cmdline_parser_arg_type arg_type,
               int check_ambiguity, int override,
               int no_free, int multiple_option,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  char *stop_char = 0;
  const char *val = value;
  int found;
  char **string_field;
  FIX_UNUSED (field);

  stop_char = 0;
  found = 0;

  if (!multiple_option && prev_given && (*prev_given || (check_ambiguity && *field_given)))
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: `--%s' (`-%c') option given more than once%s\n", 
               package_name, long_opt, short_opt,
               (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: `--%s' option given more than once%s\n", 
               package_name, long_opt,
               (additional_error ? additional_error : ""));
      return 1; /* failure */
    }

  if (possible_values && (found = check_possible_values((value ? value : default_value), possible_values)) < 0)
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: %s argument, \"%s\", for option `--%s' (`-%c')%s\n", 
          package_name, (found == -2) ? "ambiguous" : "invalid", value, long_opt, short_opt,
          (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: %s argument, \"%s\", for option `--%s'%s\n", 
          package_name, (found == -2) ? "ambiguous" : "invalid", value, long_opt,
          (additional_error ? additional_error : ""));
      return 1; /* failure */
    }
    
  if (field_given && *field_given && ! override)
    return 0;
  if (prev_given)
    (*prev_given)++;
  if (field_given)
    (*field_given)++;
  if (possible_values)
    val = possible_values[found];

  switch(arg_type) {
  case ARG_FLAG:
    *((int *)field) = !*((int *)field);
    break;
  case ARG_INT:
    if (val) *((int *)field) = strtol (val, &stop_char, 0);
    break;
  case ARG_LONG:
    if (val) *((long *)field) = (long)strtol (val, &stop_char, 0);
    break;
  case ARG_STRING:
    if (val) {
      string_field = (char **)field;
      if (!no_free && *string_field)
        free (*string_field); /* free previous string */
      *string_field = gengetopt_strdup (val);
    }
    break;
  default:
    break;
  };

  /* check numeric conversion */
  switch(arg_type) {
  case ARG_INT:
  case ARG_LONG:
    if (val && !(stop_char && *stop_char == '\0')) {
      fprintf(stderr, "%s: invalid numeric value: %s\n", package_name, val);
      return 1; /* failure */
    }
    break;
  default:
    ;
  };

  /* store the original value */
  switch(arg_type) {
  case ARG_NO:
  case ARG_FLAG:
    break;
  default:
    if (value && orig_field) {
      if (no_free) {
        *orig_field = value;
      } else {
        if (*orig_field)
          free (*orig_field); /* free previous string */
        *orig_field = gengetopt_strdup (value);
      }
    }
  };

  return 0; /* OK */
}


int
cmdline_parser_internal (
  int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error_occurred = 0;
  struct gengetopt_args_info local_args_info;
  
  int override;
  int initialize;
  int check_required;
  int check_ambiguity;
  
  package_name = argv[0];
  
  /* TODO: Why is this here? It is not used anywhere. */
  override = params->override;
  FIX_UNUSED(override);

  initialize = params->initialize;
  check_required = params->check_required;

  /* TODO: Why is this here? It is not used anywhere. */
  check_ambiguity = params->check_ambiguity;
  FIX_UNUSED(check_ambiguity);

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = params->print_errors;
  optopt = '?';

  while (1)
    {
      int option_index = 0;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "num-trials",	1, NULL, 0 },
        { "ops-per-trial",	1, NULL, 0 },
        { "bytes-per-op",	1, NULL, 0 },
        { "num-ost",	1, NULL, 0 },
        { "num-stripe",	1, NULL, 0 },
        { "stripe-size",	1, NULL, 0 },
        { "async",	0, NULL, 0 },
        { "in-transit",	1, NULL, 0 },
        { "result-file",	1, NULL, 0 },
        { "result-file-mode",	1, NULL, 0 },
        { "scratch-file",	1, NULL, 0 },
        { "remove-file",	0, NULL, 0 },
        { "lwfs-config-file",	1, NULL, 0 },
        { 0,  0, 0, 0 }
      };

      c = getopt_long (argc, argv, "hV", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cmdline_parser_print_help ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          cmdline_parser_print_version ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);


        case 0:	/* Long option with no short option */
          /* The number of trials per experiment.  */
          if (strcmp (long_options[option_index].name, "num-trials") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->num_trials_arg), 
                 &(args_info->num_trials_orig), &(args_info->num_trials_given),
                &(local_args_info.num_trials_given), optarg, 0, "1", ARG_INT,
                check_ambiguity, override, 0, 0,
                "num-trials", '-',
                additional_error))
              goto failure;
          
          }
          /* The number of operations in a trial (blocksize=ops_per_trial*bytes_per_op).  */
          else if (strcmp (long_options[option_index].name, "ops-per-trial") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->ops_per_trial_arg), 
                 &(args_info->ops_per_trial_orig), &(args_info->ops_per_trial_given),
                &(local_args_info.ops_per_trial_given), optarg, 0, "1", ARG_INT,
                check_ambiguity, override, 0, 0,
                "ops-per-trial", '-',
                additional_error))
              goto failure;
          
          }
          /* The number of bytes/object.  */
          else if (strcmp (long_options[option_index].name, "bytes-per-op") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->bytes_per_op_arg), 
                 &(args_info->bytes_per_op_orig), &(args_info->bytes_per_op_given),
                &(local_args_info.bytes_per_op_given), optarg, 0, "1024", ARG_INT,
                check_ambiguity, override, 0, 0,
                "bytes-per-op", '-',
                additional_error))
              goto failure;
          
          }
          /* The number of object storage targets.  */
          else if (strcmp (long_options[option_index].name, "num-ost") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->num_ost_arg), 
                 &(args_info->num_ost_orig), &(args_info->num_ost_given),
                &(local_args_info.num_ost_given), optarg, 0, "1", ARG_INT,
                check_ambiguity, override, 0, 0,
                "num-ost", '-',
                additional_error))
              goto failure;
          
          }
          /* The number of stripes/file.  */
          else if (strcmp (long_options[option_index].name, "num-stripe") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->num_stripe_arg), 
                 &(args_info->num_stripe_orig), &(args_info->num_stripe_given),
                &(local_args_info.num_stripe_given), optarg, 0, "1", ARG_INT,
                check_ambiguity, override, 0, 0,
                "num-stripe", '-',
                additional_error))
              goto failure;
          
          }
          /* The size of a stripe.  */
          else if (strcmp (long_options[option_index].name, "stripe-size") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->stripe_size_arg), 
                 &(args_info->stripe_size_orig), &(args_info->stripe_size_given),
                &(local_args_info.stripe_size_given), optarg, 0, "1", ARG_LONG,
                check_ambiguity, override, 0, 0,
                "stripe-size", '-',
                additional_error))
              goto failure;
          
          }
          /* Asynchronous tests.  */
          else if (strcmp (long_options[option_index].name, "async") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->async_flag), 0, &(args_info->async_given),
                &(local_args_info.async_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "async", '-',
                additional_error))
              goto failure;
          
          }
          /* Number of requests in transit.  */
          else if (strcmp (long_options[option_index].name, "in-transit") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->in_transit_arg), 
                 &(args_info->in_transit_orig), &(args_info->in_transit_given),
                &(local_args_info.in_transit_given), optarg, 0, "10", ARG_INT,
                check_ambiguity, override, 0, 0,
                "in-transit", '-',
                additional_error))
              goto failure;
          
          }
          /* Where to store results.  */
          else if (strcmp (long_options[option_index].name, "result-file") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->result_file_arg), 
                 &(args_info->result_file_orig), &(args_info->result_file_given),
                &(local_args_info.result_file_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "result-file", '-',
                additional_error))
              goto failure;
          
          }
          /* Write mode for the result.  */
          else if (strcmp (long_options[option_index].name, "result-file-mode") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->result_file_mode_arg), 
                 &(args_info->result_file_mode_orig), &(args_info->result_file_mode_given),
                &(local_args_info.result_file_mode_given), optarg, cmdline_parser_result_file_mode_values, "write", ARG_STRING,
                check_ambiguity, override, 0, 0,
                "result-file-mode", '-',
                additional_error))
              goto failure;
          
          }
          /* Where to write scratch data.  */
          else if (strcmp (long_options[option_index].name, "scratch-file") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->scratch_file_arg), 
                 &(args_info->scratch_file_orig), &(args_info->scratch_file_given),
                &(local_args_info.scratch_file_given), optarg, 0, "/usr/tmp/scratch", ARG_STRING,
                check_ambiguity, override, 0, 0,
                "scratch-file", '-',
                additional_error))
              goto failure;
          
          }
          /* Remove the file when finished.  */
          else if (strcmp (long_options[option_index].name, "remove-file") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->remove_file_flag), 0, &(args_info->remove_file_given),
                &(local_args_info.remove_file_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "remove-file", '-',
                additional_error))
              goto failure;
          
          }
          /* Configuration file for LWFS services.  */
          else if (strcmp (long_options[option_index].name, "lwfs-config-file") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->lwfs_config_file_arg), 
                 &(args_info->lwfs_config_file_orig), &(args_info->lwfs_config_file_given),
                &(local_args_info.lwfs_config_file_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "lwfs-config-file", '-',
                additional_error))
              goto failure;
          
          }
          
          break;
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */



  if (check_required)
    {
      error_occurred += cmdline_parser_required2 (args_info, argv[0], additional_error);
    }

  cmdline_parser_release (&local_args_info);

  if ( error_occurred )
    return (EXIT_FAILURE);

  return 0;

failure:
  
  cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}

static unsigned int
cmdline_parser_create_argv(const char *cmdline_, char ***argv_ptr, const char *prog_name)
{
  char *cmdline, *p;
  size_t n = 0, j;
  int i;

  if (prog_name) {
    cmd_line_list_tmp = (struct line_list *) malloc (sizeof (struct line_list));
    cmd_line_list_tmp->next = cmd_line_list;
    cmd_line_list = cmd_line_list_tmp;
    cmd_line_list->string_arg = gengetopt_strdup (prog_name);

    ++n;
  }

  cmdline = gengetopt_strdup(cmdline_);
  p = cmdline;

  while (p && strlen(p))
    {
      j = strcspn(p, " \t");
      ++n;
      if (j && j < strlen(p))
        {
          p[j] = '\0';

          cmd_line_list_tmp = (struct line_list *) malloc (sizeof (struct line_list));
          cmd_line_list_tmp->next = cmd_line_list;
          cmd_line_list = cmd_line_list_tmp;
          cmd_line_list->string_arg = gengetopt_strdup (p);

          p += (j+1);
          p += strspn(p, " \t");
        }
      else
        {
          cmd_line_list_tmp = (struct line_list *) malloc (sizeof (struct line_list));
          cmd_line_list_tmp->next = cmd_line_list;
          cmd_line_list = cmd_line_list_tmp;
          cmd_line_list->string_arg = gengetopt_strdup (p);

          break;
        }
    }

  *argv_ptr = (char **) malloc((n + 1) * sizeof(char *));
  cmd_line_list_tmp = cmd_line_list;
  for (i = (n-1); i >= 0; --i)
    {
      (*argv_ptr)[i] = cmd_line_list_tmp->string_arg;
      cmd_line_list_tmp = cmd_line_list_tmp->next;
    }

  (*argv_ptr)[n] = 0;

  free(cmdline);
  return n;
}

int
cmdline_parser_string(const char *cmdline, struct gengetopt_args_info *args_info, const char *prog_name)
{
  return cmdline_parser_string2(cmdline, args_info, prog_name, 0, 1, 1);
}

int
cmdline_parser_string2(const char *cmdline, struct gengetopt_args_info *args_info, const char *prog_name,
    int override, int initialize, int check_required)
{
  struct cmdline_parser_params params;

  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  return cmdline_parser_string_ext(cmdline, args_info, prog_name, &params);
}

int
cmdline_parser_string_ext(const char *cmdline, struct gengetopt_args_info *args_info, const char *prog_name,
    struct cmdline_parser_params *params)
{
  char **argv_ptr = 0;
  int result;
  unsigned int argc;
  
  argc = cmdline_parser_create_argv(cmdline, &argv_ptr, prog_name);
  
  result =
    cmdline_parser_internal (argc, argv_ptr, args_info, params, 0);
  
  if (argv_ptr)
    {
      free (argv_ptr);
    }

  free_cmd_list();
  
  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

/* vim: set ft=c noet ts=8 sts=8 sw=8 tw=80 nojs spell : */
