/** @file lwfs-opts.h
 *  @brief The header file for the command line option parser
 *  generated by GNU Gengetopt version 2.23
 *  http://www.gnu.org/software/gengetopt.
 *  DO NOT modify this file, since it can be overwritten
 *  @author GNU Gengetopt */

#ifndef LWFS_OPTS_H
#define LWFS_OPTS_H

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h> /* for FILE */

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef CMDLINE_PARSER_PACKAGE
/** @brief the program name (used for printing errors) */
#define CMDLINE_PARSER_PACKAGE "lwfs-tests"
#endif

#ifndef CMDLINE_PARSER_PACKAGE_NAME
/** @brief the complete program name (used for help and version) */
#define CMDLINE_PARSER_PACKAGE_NAME "lwfs-tests"
#endif

#ifndef CMDLINE_PARSER_VERSION
/** @brief the program version */
#define CMDLINE_PARSER_VERSION "0.1"
#endif

/** @brief Where the command line options are stored */
struct gengetopt_args_info
{
  const char *help_help; /**< @brief Print help and exit help description.  */
  const char *version_help; /**< @brief Print version and exit help description.  */
  int num_trials_arg;	/**< @brief The number of trials per experiment (default='1').  */
  char * num_trials_orig;	/**< @brief The number of trials per experiment original value given at command line.  */
  const char *num_trials_help; /**< @brief The number of trials per experiment help description.  */
  int ops_per_trial_arg;	/**< @brief The number of operations in a trial (blocksize=ops_per_trial*bytes_per_op) (default='1').  */
  char * ops_per_trial_orig;	/**< @brief The number of operations in a trial (blocksize=ops_per_trial*bytes_per_op) original value given at command line.  */
  const char *ops_per_trial_help; /**< @brief The number of operations in a trial (blocksize=ops_per_trial*bytes_per_op) help description.  */
  int bytes_per_op_arg;	/**< @brief The number of bytes/object (default='1024').  */
  char * bytes_per_op_orig;	/**< @brief The number of bytes/object original value given at command line.  */
  const char *bytes_per_op_help; /**< @brief The number of bytes/object help description.  */
  int num_ost_arg;	/**< @brief The number of object storage targets (default='1').  */
  char * num_ost_orig;	/**< @brief The number of object storage targets original value given at command line.  */
  const char *num_ost_help; /**< @brief The number of object storage targets help description.  */
  int num_stripe_arg;	/**< @brief The number of stripes/file (default='1').  */
  char * num_stripe_orig;	/**< @brief The number of stripes/file original value given at command line.  */
  const char *num_stripe_help; /**< @brief The number of stripes/file help description.  */
  long stripe_size_arg;	/**< @brief The size of a stripe (default='1').  */
  char * stripe_size_orig;	/**< @brief The size of a stripe original value given at command line.  */
  const char *stripe_size_help; /**< @brief The size of a stripe help description.  */
  int async_flag;	/**< @brief Asynchronous tests (default=off).  */
  const char *async_help; /**< @brief Asynchronous tests help description.  */
  int in_transit_arg;	/**< @brief Number of requests in transit (default='10').  */
  char * in_transit_orig;	/**< @brief Number of requests in transit original value given at command line.  */
  const char *in_transit_help; /**< @brief Number of requests in transit help description.  */
  char * result_file_arg;	/**< @brief Where to store results.  */
  char * result_file_orig;	/**< @brief Where to store results original value given at command line.  */
  const char *result_file_help; /**< @brief Where to store results help description.  */
  char * result_file_mode_arg;	/**< @brief Write mode for the result (default='write').  */
  char * result_file_mode_orig;	/**< @brief Write mode for the result original value given at command line.  */
  const char *result_file_mode_help; /**< @brief Write mode for the result help description.  */
  char * scratch_file_arg;	/**< @brief Where to write scratch data (default='/usr/tmp/scratch').  */
  char * scratch_file_orig;	/**< @brief Where to write scratch data original value given at command line.  */
  const char *scratch_file_help; /**< @brief Where to write scratch data help description.  */
  int remove_file_flag;	/**< @brief Remove the file when finished (default=off).  */
  const char *remove_file_help; /**< @brief Remove the file when finished help description.  */
  char * lwfs_config_file_arg;	/**< @brief Configuration file for LWFS services.  */
  char * lwfs_config_file_orig;	/**< @brief Configuration file for LWFS services original value given at command line.  */
  const char *lwfs_config_file_help; /**< @brief Configuration file for LWFS services help description.  */
  
  unsigned int help_given ;	/**< @brief Whether help was given.  */
  unsigned int version_given ;	/**< @brief Whether version was given.  */
  unsigned int num_trials_given ;	/**< @brief Whether num-trials was given.  */
  unsigned int ops_per_trial_given ;	/**< @brief Whether ops-per-trial was given.  */
  unsigned int bytes_per_op_given ;	/**< @brief Whether bytes-per-op was given.  */
  unsigned int num_ost_given ;	/**< @brief Whether num-ost was given.  */
  unsigned int num_stripe_given ;	/**< @brief Whether num-stripe was given.  */
  unsigned int stripe_size_given ;	/**< @brief Whether stripe-size was given.  */
  unsigned int async_given ;	/**< @brief Whether async was given.  */
  unsigned int in_transit_given ;	/**< @brief Whether in-transit was given.  */
  unsigned int result_file_given ;	/**< @brief Whether result-file was given.  */
  unsigned int result_file_mode_given ;	/**< @brief Whether result-file-mode was given.  */
  unsigned int scratch_file_given ;	/**< @brief Whether scratch-file was given.  */
  unsigned int remove_file_given ;	/**< @brief Whether remove-file was given.  */
  unsigned int lwfs_config_file_given ;	/**< @brief Whether lwfs-config-file was given.  */

} ;

/** @brief The additional parameters to pass to parser functions */
struct cmdline_parser_params
{
  int override; /**< @brief whether to override possibly already present options (default 0) */
  int initialize; /**< @brief whether to initialize the option structure gengetopt_args_info (default 1) */
  int check_required; /**< @brief whether to check that all required options were provided (default 1) */
  int check_ambiguity; /**< @brief whether to check for options already specified in the option structure gengetopt_args_info (default 0) */
  int print_errors; /**< @brief whether getopt_long should print an error message for a bad option (default 1) */
} ;

/** @brief the purpose string of the program */
extern const char *gengetopt_args_info_purpose;
/** @brief the usage string of the program */
extern const char *gengetopt_args_info_usage;
/** @brief the description string of the program */
extern const char *gengetopt_args_info_description;
/** @brief all the lines making the help output */
extern const char *gengetopt_args_info_help[];

/**
 * The command line parser
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser (int argc, char **argv,
  struct gengetopt_args_info *args_info);

/**
 * The command line parser (version with additional parameters - deprecated)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param override whether to override possibly already present options
 * @param initialize whether to initialize the option structure my_args_info
 * @param check_required whether to check that all required options were provided
 * @return 0 if everything went fine, NON 0 if an error took place
 * @deprecated use cmdline_parser_ext() instead
 */
int cmdline_parser2 (int argc, char **argv,
  struct gengetopt_args_info *args_info,
  int override, int initialize, int check_required);

/**
 * The command line parser (version with additional parameters)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param params additional parameters for the parser
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_ext (int argc, char **argv,
  struct gengetopt_args_info *args_info,
  struct cmdline_parser_params *params);

/**
 * Save the contents of the option struct into an already open FILE stream.
 * @param outfile the stream where to dump options
 * @param args_info the option struct to dump
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_dump(FILE *outfile,
  struct gengetopt_args_info *args_info);

/**
 * Save the contents of the option struct into a (text) file.
 * This file can be read by the config file parser (if generated by gengetopt)
 * @param filename the file where to save
 * @param args_info the option struct to save
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_file_save(const char *filename,
  struct gengetopt_args_info *args_info);

/**
 * Print the help
 */
void cmdline_parser_print_help(void);
/**
 * Print the version
 */
void cmdline_parser_print_version(void);

/**
 * Initializes all the fields a cmdline_parser_params structure 
 * to their default values
 * @param params the structure to initialize
 */
void cmdline_parser_params_init(struct cmdline_parser_params *params);

/**
 * Allocates dynamically a cmdline_parser_params structure and initializes
 * all its fields to their default values
 * @return the created and initialized cmdline_parser_params structure
 */
struct cmdline_parser_params *cmdline_parser_params_create(void);

/**
 * Initializes the passed gengetopt_args_info structure's fields
 * (also set default values for options that have a default)
 * @param args_info the structure to initialize
 */
void cmdline_parser_init (struct gengetopt_args_info *args_info);
/**
 * Deallocates the string fields of the gengetopt_args_info structure
 * (but does not deallocate the structure itself)
 * @param args_info the structure to deallocate
 */
void cmdline_parser_free (struct gengetopt_args_info *args_info);

/**
 * The string parser (interprets the passed string as a command line)
 * @param cmdline the command line stirng
 * @param args_info the structure where option information will be stored
 * @param prog_name the name of the program that will be used to print
 *   possible errors
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_string (const char *cmdline, struct gengetopt_args_info *args_info,
  const char *prog_name);
/**
 * The string parser (version with additional parameters - deprecated)
 * @param cmdline the command line stirng
 * @param args_info the structure where option information will be stored
 * @param prog_name the name of the program that will be used to print
 *   possible errors
 * @param override whether to override possibly already present options
 * @param initialize whether to initialize the option structure my_args_info
 * @param check_required whether to check that all required options were provided
 * @return 0 if everything went fine, NON 0 if an error took place
 * @deprecated use cmdline_parser_string_ext() instead
 */
int cmdline_parser_string2 (const char *cmdline, struct gengetopt_args_info *args_info,
  const char *prog_name,
  int override, int initialize, int check_required);
/**
 * The string parser (version with additional parameters)
 * @param cmdline the command line stirng
 * @param args_info the structure where option information will be stored
 * @param prog_name the name of the program that will be used to print
 *   possible errors
 * @param params additional parameters for the parser
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_string_ext (const char *cmdline, struct gengetopt_args_info *args_info,
  const char *prog_name,
  struct cmdline_parser_params *params);

/**
 * Checks that all the required options were specified
 * @param args_info the structure to check
 * @param prog_name the name of the program that will be used to print
 *   possible errors
 * @return
 */
int cmdline_parser_required (struct gengetopt_args_info *args_info,
  const char *prog_name);

extern const char *cmdline_parser_result_file_mode_values[];  /**< @brief Possible values for result-file-mode. */


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* LWFS_OPTS_H */
