/** @file cmdline.h
 *  @brief The header file for the command line option parser
 *  generated by GNU Gengetopt version 2.23
 *  http://www.gnu.org/software/gengetopt.
 *  DO NOT modify this file, since it can be overwritten
 *  @author GNU Gengetopt */

#ifndef CMDLINE_H
#define CMDLINE_H

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h> /* for FILE */

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef CMDLINE_PARSER_PACKAGE
/** @brief the program name (used for printing errors) */
#define CMDLINE_PARSER_PACKAGE "lwfs"
#endif

#ifndef CMDLINE_PARSER_PACKAGE_NAME
/** @brief the complete program name (used for help and version) */
#define CMDLINE_PARSER_PACKAGE_NAME "lwfs"
#endif

#ifndef CMDLINE_PARSER_VERSION
/** @brief the program version */
#define CMDLINE_PARSER_VERSION "0.1"
#endif

/** @brief Where the command line options are stored */
struct gengetopt_args_info
{
  const char *help_help; /**< @brief Print help and exit help description.  */
  const char *version_help; /**< @brief Print version and exit help description.  */
  int num_reqs_arg;	/**< @brief Number of requests before exit (default='-1').  */
  char * num_reqs_orig;	/**< @brief Number of requests before exit original value given at command line.  */
  const char *num_reqs_help; /**< @brief Number of requests before exit help description.  */
  int use_threads_flag;	/**< @brief Flag to use threads for the server (default=off).  */
  const char *use_threads_help; /**< @brief Flag to use threads for the server help description.  */
  int daemon_flag;	/**< @brief Flag to run server as a daemon (default=off).  */
  const char *daemon_help; /**< @brief Flag to run server as a daemon help description.  */
  int naming_pid_arg;	/**< @brief The process ID to use for the naming server (default='126').  */
  char * naming_pid_orig;	/**< @brief The process ID to use for the naming server original value given at command line.  */
  const char *naming_pid_help; /**< @brief The process ID to use for the naming server help description.  */
  char * naming_db_path_arg;	/**< @brief Path to the naming database (default='naming.db').  */
  char * naming_db_path_orig;	/**< @brief Path to the naming database original value given at command line.  */
  const char *naming_db_path_help; /**< @brief Path to the naming database help description.  */
  int naming_db_clear_flag;	/**< @brief Clear the naming database before use (default=off).  */
  const char *naming_db_clear_help; /**< @brief Clear the naming database before use help description.  */
  int naming_db_recover_flag;	/**< @brief Recover the naming database after a crash (default=off).  */
  const char *naming_db_recover_help; /**< @brief Recover the naming database after a crash help description.  */
  int verbose_arg;	/**< @brief Debug level of logger [0-5] (default='5').  */
  char * verbose_orig;	/**< @brief Debug level of logger [0-5] original value given at command line.  */
  const char *verbose_help; /**< @brief Debug level of logger [0-5] help description.  */
  char * logfile_arg;	/**< @brief Path to logfile.  */
  char * logfile_orig;	/**< @brief Path to logfile original value given at command line.  */
  const char *logfile_help; /**< @brief Path to logfile help description.  */
  int tp_init_thread_count_arg;	/**< @brief Initial number of thread in the pool (default='1').  */
  char * tp_init_thread_count_orig;	/**< @brief Initial number of thread in the pool original value given at command line.  */
  const char *tp_init_thread_count_help; /**< @brief Initial number of thread in the pool help description.  */
  int tp_min_thread_count_arg;	/**< @brief Minimum number of thread in the pool (default='1').  */
  char * tp_min_thread_count_orig;	/**< @brief Minimum number of thread in the pool original value given at command line.  */
  const char *tp_min_thread_count_help; /**< @brief Minimum number of thread in the pool help description.  */
  int tp_max_thread_count_arg;	/**< @brief Maximum number of thread in the pool (default='999999999').  */
  char * tp_max_thread_count_orig;	/**< @brief Maximum number of thread in the pool original value given at command line.  */
  const char *tp_max_thread_count_help; /**< @brief Maximum number of thread in the pool help description.  */
  int tp_low_watermark_arg;	/**< @brief Request queue size at which threads are removed from the pool (default='1').  */
  char * tp_low_watermark_orig;	/**< @brief Request queue size at which threads are removed from the pool original value given at command line.  */
  const char *tp_low_watermark_help; /**< @brief Request queue size at which threads are removed from the pool help description.  */
  int tp_high_watermark_arg;	/**< @brief Request queue size at which threads are added to the pool (default='999999999').  */
  char * tp_high_watermark_orig;	/**< @brief Request queue size at which threads are added to the pool original value given at command line.  */
  const char *tp_high_watermark_help; /**< @brief Request queue size at which threads are added to the pool help description.  */
  int max_mem_allowed_arg;	/**< @brief System memory usage in kilobytes that causes this process to commit suicide (default='0').  */
  char * max_mem_allowed_orig;	/**< @brief System memory usage in kilobytes that causes this process to commit suicide original value given at command line.  */
  const char *max_mem_allowed_help; /**< @brief System memory usage in kilobytes that causes this process to commit suicide help description.  */
  long authr_pid_arg;	/**< @brief PID of the authr server (default='124').  */
  char * authr_pid_orig;	/**< @brief PID of the authr server original value given at command line.  */
  const char *authr_pid_help; /**< @brief PID of the authr server help description.  */
  long authr_nid_arg;	/**< @brief NID of the authr server (default='0').  */
  char * authr_nid_orig;	/**< @brief NID of the authr server original value given at command line.  */
  const char *authr_nid_help; /**< @brief NID of the authr server help description.  */
  int authr_cache_caps_flag;	/**< @brief Cache caps on the client (default=off).  */
  const char *authr_cache_caps_help; /**< @brief Cache caps on the client help description.  */
  
  unsigned int help_given ;	/**< @brief Whether help was given.  */
  unsigned int version_given ;	/**< @brief Whether version was given.  */
  unsigned int num_reqs_given ;	/**< @brief Whether num-reqs was given.  */
  unsigned int use_threads_given ;	/**< @brief Whether use-threads was given.  */
  unsigned int daemon_given ;	/**< @brief Whether daemon was given.  */
  unsigned int naming_pid_given ;	/**< @brief Whether naming-pid was given.  */
  unsigned int naming_db_path_given ;	/**< @brief Whether naming-db-path was given.  */
  unsigned int naming_db_clear_given ;	/**< @brief Whether naming-db-clear was given.  */
  unsigned int naming_db_recover_given ;	/**< @brief Whether naming-db-recover was given.  */
  unsigned int verbose_given ;	/**< @brief Whether verbose was given.  */
  unsigned int logfile_given ;	/**< @brief Whether logfile was given.  */
  unsigned int tp_init_thread_count_given ;	/**< @brief Whether tp-init-thread-count was given.  */
  unsigned int tp_min_thread_count_given ;	/**< @brief Whether tp-min-thread-count was given.  */
  unsigned int tp_max_thread_count_given ;	/**< @brief Whether tp-max-thread-count was given.  */
  unsigned int tp_low_watermark_given ;	/**< @brief Whether tp-low-watermark was given.  */
  unsigned int tp_high_watermark_given ;	/**< @brief Whether tp-high-watermark was given.  */
  unsigned int max_mem_allowed_given ;	/**< @brief Whether max-mem-allowed was given.  */
  unsigned int authr_pid_given ;	/**< @brief Whether authr-pid was given.  */
  unsigned int authr_nid_given ;	/**< @brief Whether authr-nid was given.  */
  unsigned int authr_cache_caps_given ;	/**< @brief Whether authr-cache-caps was given.  */

} ;

/** @brief The additional parameters to pass to parser functions */
struct cmdline_parser_params
{
  int override; /**< @brief whether to override possibly already present options (default 0) */
  int initialize; /**< @brief whether to initialize the option structure gengetopt_args_info (default 1) */
  int check_required; /**< @brief whether to check that all required options were provided (default 1) */
  int check_ambiguity; /**< @brief whether to check for options already specified in the option structure gengetopt_args_info (default 0) */
  int print_errors; /**< @brief whether getopt_long should print an error message for a bad option (default 1) */
} ;

/** @brief the purpose string of the program */
extern const char *gengetopt_args_info_purpose;
/** @brief the usage string of the program */
extern const char *gengetopt_args_info_usage;
/** @brief the description string of the program */
extern const char *gengetopt_args_info_description;
/** @brief all the lines making the help output */
extern const char *gengetopt_args_info_help[];

/**
 * The command line parser
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser (int argc, char **argv,
  struct gengetopt_args_info *args_info);

/**
 * The command line parser (version with additional parameters - deprecated)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param override whether to override possibly already present options
 * @param initialize whether to initialize the option structure my_args_info
 * @param check_required whether to check that all required options were provided
 * @return 0 if everything went fine, NON 0 if an error took place
 * @deprecated use cmdline_parser_ext() instead
 */
int cmdline_parser2 (int argc, char **argv,
  struct gengetopt_args_info *args_info,
  int override, int initialize, int check_required);

/**
 * The command line parser (version with additional parameters)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param params additional parameters for the parser
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_ext (int argc, char **argv,
  struct gengetopt_args_info *args_info,
  struct cmdline_parser_params *params);

/**
 * Save the contents of the option struct into an already open FILE stream.
 * @param outfile the stream where to dump options
 * @param args_info the option struct to dump
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_dump(FILE *outfile,
  struct gengetopt_args_info *args_info);

/**
 * Save the contents of the option struct into a (text) file.
 * This file can be read by the config file parser (if generated by gengetopt)
 * @param filename the file where to save
 * @param args_info the option struct to save
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_file_save(const char *filename,
  struct gengetopt_args_info *args_info);

/**
 * Print the help
 */
void cmdline_parser_print_help(void);
/**
 * Print the version
 */
void cmdline_parser_print_version(void);

/**
 * Initializes all the fields a cmdline_parser_params structure 
 * to their default values
 * @param params the structure to initialize
 */
void cmdline_parser_params_init(struct cmdline_parser_params *params);

/**
 * Allocates dynamically a cmdline_parser_params structure and initializes
 * all its fields to their default values
 * @return the created and initialized cmdline_parser_params structure
 */
struct cmdline_parser_params *cmdline_parser_params_create(void);

/**
 * Initializes the passed gengetopt_args_info structure's fields
 * (also set default values for options that have a default)
 * @param args_info the structure to initialize
 */
void cmdline_parser_init (struct gengetopt_args_info *args_info);
/**
 * Deallocates the string fields of the gengetopt_args_info structure
 * (but does not deallocate the structure itself)
 * @param args_info the structure to deallocate
 */
void cmdline_parser_free (struct gengetopt_args_info *args_info);

/**
 * The string parser (interprets the passed string as a command line)
 * @param cmdline the command line stirng
 * @param args_info the structure where option information will be stored
 * @param prog_name the name of the program that will be used to print
 *   possible errors
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_string (const char *cmdline, struct gengetopt_args_info *args_info,
  const char *prog_name);
/**
 * The string parser (version with additional parameters - deprecated)
 * @param cmdline the command line stirng
 * @param args_info the structure where option information will be stored
 * @param prog_name the name of the program that will be used to print
 *   possible errors
 * @param override whether to override possibly already present options
 * @param initialize whether to initialize the option structure my_args_info
 * @param check_required whether to check that all required options were provided
 * @return 0 if everything went fine, NON 0 if an error took place
 * @deprecated use cmdline_parser_string_ext() instead
 */
int cmdline_parser_string2 (const char *cmdline, struct gengetopt_args_info *args_info,
  const char *prog_name,
  int override, int initialize, int check_required);
/**
 * The string parser (version with additional parameters)
 * @param cmdline the command line stirng
 * @param args_info the structure where option information will be stored
 * @param prog_name the name of the program that will be used to print
 *   possible errors
 * @param params additional parameters for the parser
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_string_ext (const char *cmdline, struct gengetopt_args_info *args_info,
  const char *prog_name,
  struct cmdline_parser_params *params);

/**
 * Checks that all the required options were specified
 * @param args_info the structure to check
 * @param prog_name the name of the program that will be used to print
 *   possible errors
 * @return
 */
int cmdline_parser_required (struct gengetopt_args_info *args_info,
  const char *prog_name);


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* CMDLINE_H */
